import { ChangeDetectorRef, ElementRef, EventEmitter, OnChanges, OnInit, Renderer2, SimpleChanges } from '@angular/core';
import { GuiSelectOption } from './select-option';
import { SelectOptionsGeometryService } from './options/select-options-geometry.service';
import { FabricSelectedOptionsRepository } from './selected-option.repository';
import { SelectOptionModalService } from './select-option-modal.service';
import { FabricReactive } from '../../common/fabric-reactive';
export declare class FabricSelectComponent extends FabricReactive implements OnInit, OnChanges {
    private readonly selectService;
    private readonly selectOptionsGeometryService;
    private readonly selectOptionModalService;
    private readonly changeDetectorRef;
    private readonly platformId;
    private readonly elementRef;
    private readonly renderer;
    containerRef: ElementRef;
    options: Array<GuiSelectOption>;
    placeholder: string;
    selected: GuiSelectOption;
    width: number;
    disabled: boolean;
    optionChanged: EventEmitter<GuiSelectOption>;
    selectedOption: GuiSelectOption;
    containerText: string;
    private scrollListenerFn;
    private doNotEmitValues;
    private opened;
    constructor(selectService: FabricSelectedOptionsRepository, selectOptionsGeometryService: SelectOptionsGeometryService, selectOptionModalService: SelectOptionModalService, changeDetectorRef: ChangeDetectorRef, platformId: any, elementRef: ElementRef, renderer: Renderer2);
    ngOnChanges(changes: SimpleChanges): void;
    ngOnInit(): void;
    tryToOpen(event: any): void;
    clickOutside(event: any): void;
    toggleOptions(opened: boolean): void;
    isOptionSelected(option: GuiSelectOption): boolean;
    getOptionValue(option: GuiSelectOption): string;
    private open;
    private tryToSelect;
    private maintainOptionsListPosition;
    private closeSelect;
    private emitSelectedOption;
    private openDownward;
    private openUpward;
    private closeOptions;
    private isContainerClicked;
    private isContainerDisabled;
    private addClass;
    private removeClass;
}
