import { ChangeDetectorRef, ElementRef, OnInit } from '@angular/core';
import { SmartComponent } from '../../../common/cdk/component/smart-component';
import { Paging } from '../core/api/read/paging';
import { PagingWarehouse } from '../core/api/paging.warehouse';
import { PagingCommandInvoker } from '../core/api/paging.command-invoker';
import { SourceWarehouse } from '../../source/core/api/source.warehouse';
import { PagingDisplayModeArchive } from './mode/paging-display-mode.archive';
import { PagingPosition } from './paging-position';
import { CssClassModifier } from '../../common/css-class/css-class.modifier';
import { NgChanges } from '../../../common/cdk/component/ng-changes';
import { StructureId } from '../../core/api/structure.id';
import * as i0 from "@angular/core";
export declare class PagingComponent extends SmartComponent implements OnInit {
    private readonly elRef;
    private readonly changeDetectorRef;
    private readonly cssClassModifier;
    private readonly structureId;
    private readonly pagingWarehouse;
    private readonly pagingCommandInvoker;
    private readonly sourceWarehouse;
    private readonly pagingDisplayModeArchive;
    position: PagingPosition;
    minimal: boolean;
    sourceSize: number;
    paging: Paging;
    alternativeDisplay: boolean;
    isPagingVisible: boolean;
    private readonly localStreamCloser;
    constructor(elRef: ElementRef, changeDetectorRef: ChangeDetectorRef, cssClassModifier: CssClassModifier, structureId: StructureId, pagingWarehouse: PagingWarehouse, pagingCommandInvoker: PagingCommandInvoker, sourceWarehouse: SourceWarehouse, pagingDisplayModeArchive: PagingDisplayModeArchive);
    ngOnChanges(changes: NgChanges<PagingComponent>): void;
    ngOnInit(): void;
    ngOnDestroy(): void;
    changePageSize(pageSize: number): void;
    nextPage(): void;
    prevPage(): void;
    private calculatePagingVisibility;
    protected getSelectorName(): string;
    static ɵfac: i0.ɵɵFactoryDeclaration<PagingComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<PagingComponent, "div[gui-paging][position]", never, { "position": "position"; "minimal": "minimal"; }, {}, never, never>;
}
//# sourceMappingURL=paging.component.d.ts.map