import { ChangeDetectorRef, ElementRef, OnChanges } from '@angular/core';
import { CellTemplateWithAccessor } from '../../../../../core/composition/core-read/definition/cell-template-with-accessor';
import { ChangedValueEmitter } from '../../../../../core/composition/core-read/edit/changed-value.emitter';
import { ItemEntity } from '../../../../../core/structure/source/domain/item/item.entity';
import { SmartComponent } from '../../../../../feature/common/cdk/component/smart-component';
import { SourcePublisher } from '../../../../../core/structure/source/api/source.publisher';
import { NgChanges } from '../../../../../feature/common/cdk/component/ng-changes';
import { StructureId } from '../../../../../core/structure/structure-core/api/global/structure.id';
import * as i0 from "@angular/core";
export declare class StructureCellEditComponent extends SmartComponent implements OnChanges {
    private readonly changeDetectorRef;
    private readonly structureId;
    private readonly sourceCommandService;
    readonly cellContainerRef?: ElementRef;
    entity: ItemEntity;
    cell: CellTemplateWithAccessor;
    editContext: any;
    valueChanges$: ChangedValueEmitter<any>;
    status$: ChangedValueEmitter<any>;
    actualValue: any;
    constructor(changeDetectorRef: ChangeDetectorRef, elementRef: ElementRef, structureId: StructureId, sourceCommandService: SourcePublisher);
    ngOnChanges(changes: NgChanges<StructureCellEditComponent>): void;
    ngOnInit(): void;
    submitChangesAndExit(): void;
    protected getSelectorName(): string;
    private initEditContext;
    private observeValueChanges;
    private publishEditState;
    private publishEditEnter;
    private publishEditCancel;
    private publishEditSubmit;
    static ɵfac: i0.ɵɵFactoryDeclaration<StructureCellEditComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<StructureCellEditComponent, "div[gui-structure-cell-edit][entity][cell]", never, { "entity": "entity"; "cell": "cell"; }, {}, never, never, false>;
}
