import { CellContext } from './cell-context';
import { FieldId } from '../../../../structure/field/src/domain/field/field.id';
import { SortOrder } from '../../domain/column/sort/sort-order';
import { ColumnAlign } from '../../domain/column/column-align';
import { ColumnDefinitionId } from '../../api/column/column-definition-id';
export declare class CellTemplateWithContext {
    private header;
    private dataType;
    context: CellContext;
    width: number;
    private readonly fieldId;
    private readonly columnDefinitionId;
    private readonly sortStatus;
    private readonly enabled;
    private readonly cssClasses;
    private readonly styles;
    private readonly sortable;
    private readonly align;
    constructor(header: any, dataType: any, context: CellContext, width: number, fieldId: FieldId, columnDefinitionId: ColumnDefinitionId, sortStatus: SortOrder, enabled: boolean, cssClasses: string, styles: string, sortable: boolean, align: ColumnAlign);
    getHeader(): any;
    getDataType(): any;
    getColumnDefinitionId(): ColumnDefinitionId;
    getFieldId(): FieldId;
    getSortStatus(): SortOrder;
    getCssClasses(): string;
    getStyles(): string;
    isSortEnabled(): boolean;
    isAscSort(): boolean;
    isDescSort(): boolean;
    isNoSort(): boolean;
    isEnabled(): boolean;
    isAlignLeft(): boolean;
    isAlignCenter(): boolean;
    isAlignRight(): boolean;
    getAlign(): ColumnAlign;
}
