import { ChangeDetectorRef, ElementRef, OnChanges, OnInit, Renderer2, SimpleChanges } from '@angular/core';
import { GeometryService } from './geometry.service';
import { Placement } from './placement';
export declare class FabricDropdownComponent implements OnChanges, OnInit {
    private platformId;
    private elementRef;
    private renderer;
    private changeDetectorRef;
    private geometryService;
    dropdownMenuRef: ElementRef;
    containerRef: ElementRef;
    onResize(): void;
    disabled: boolean;
    dropdownText: string;
    arrow: boolean;
    placement: Placement;
    isArrowEnabled: boolean;
    containerWidth: number;
    containerHeight: number;
    windowSize: number;
    horizontalPosition: number;
    bottomPosition: number;
    topPosition: number;
    private canOpenDownward;
    private canOpenUpward;
    private open;
    private subscription;
    constructor(platformId: any, elementRef: ElementRef, renderer: Renderer2, changeDetectorRef: ChangeDetectorRef, geometryService: GeometryService);
    ngOnChanges(changes: SimpleChanges): void;
    ngOnInit(): void;
    ngOnDestroy(): void;
    tryToOpen(event: any): void;
    clickOutside(event: any): void;
    private openMenu;
    private showItems;
    private observeGeometry;
    private openDownward;
    private openUpward;
    private openRight;
    private openLeft;
    private changePlacement;
    private hideItems;
    private isContainerClicked;
    private isContainerDisabled;
    private addClass;
    private removeClass;
}
