import { ChangeDetectorRef } from '@angular/core';
import { SmartComponent } from '../../../../common/cdk/smart-component';
import { StructureReadModelRoot } from '../../feature-api/read/structure.read-model-root';
import { StructureDefinition } from '../structure-definition';
import { StructureId } from '../../domain/structure.id';
import { StructureWarehouse } from '../../feature-api/structure.warehouse';
import { StructurePagingWarehouse } from '../../feature-api/paging/structure-paging.warehouse';
import { StructureInfoPanelEnabledArchive } from '../panel/info/structure.info-panel-enabled.archive';
import { StructureSummariesArchive } from '../panel/summaries/structure.summaries.archive';
import { StructureFilterWarehouse } from '../../feature-api/filter/structure-filter.warehouse';
import { StructureSearchWarehouse } from '../../feature-api/search/structure-search.warehouse';
import { StructureHeaderTopEnabledArchive } from '../header/structure-header-top-enabled.archive';
import { StructureHeaderBottomEnabledArchive } from '../header/structure-header-bottom-enabled.archive';
export declare class StructureBlueprintComponent extends SmartComponent {
    private readonly changeDetectorRef;
    private readonly structureDefinition;
    private readonly structureId;
    private readonly structureReadModelService;
    private readonly pagingReadModelService;
    private readonly structureInfoPanelEnabledArchive;
    private readonly structureSummariesArchive;
    private readonly structureFilterReadModelRepository;
    private readonly structureSearchReadModelRepository;
    private readonly structureHeaderTopEnabledArchive;
    private readonly structureHeaderBottomEnabledArchive;
    private className;
    structure: StructureReadModelRoot;
    searchEnabled: boolean;
    topSummariesPanelEnabled: boolean;
    bottomSummariesPanelEnabled: boolean;
    quickFiltersEnabled: boolean;
    infoPanelEnabled: boolean;
    readonly contentCssClass: string;
    readonly headerCssClass: string;
    topHeaderEnabled: boolean;
    bottomHeaderEnabled: boolean;
    private pagingReadModel;
    constructor(changeDetectorRef: ChangeDetectorRef, structureDefinition: StructureDefinition, structureId: StructureId, structureReadModelService: StructureWarehouse, pagingReadModelService: StructurePagingWarehouse, structureInfoPanelEnabledArchive: StructureInfoPanelEnabledArchive, structureSummariesArchive: StructureSummariesArchive, structureFilterReadModelRepository: StructureFilterWarehouse, structureSearchReadModelRepository: StructureSearchWarehouse, structureHeaderTopEnabledArchive: StructureHeaderTopEnabledArchive, structureHeaderBottomEnabledArchive: StructureHeaderBottomEnabledArchive, className: string);
    ngOnInit(): void;
    getHeaderTopClasses(): string;
    getHeaderBottomClasses(): string;
    isColumnHeaderTopEnabled(): boolean;
    isColumnHeaderBottomEnabled(): boolean;
    isPagingTopEnabled(): boolean;
    isPagingBottomEnabled(): boolean;
    isSourceEmpty(): boolean;
}
