import { ChangeDetectorRef } from '@angular/core';
import { SmartComponent } from '../../../../common/cdk/smart-component';
import { StructureReadModelRoot } from '../../read/structure/structure.read-model-root';
import { StructureDefinition } from '../structure-definition';
import { StructureId } from '../../domain/structure.id';
import { StructureReadModelWarehouse } from '../../ui-api/structure/structure.read-model-warehouse';
import { StructurePagingReadModelWarehouse } from '../../ui-api/paging/structure-paging.read-model-warehouse';
import { StructureInfoPanelEnabledArchive } from '../panel/info/structure.info-panel-enabled.archive';
import { StructureAggregationArchive } from '../panel/aggregation/structure.aggregation.archive';
import { StructureFilterReadModelWarehouse } from '../../ui-api/structure/filter/structure-filter.read-model-warehouse';
import { StructureSearchReadModelRepository } from '../../ui-api/structure/search/structure-search.read-model.repository';
import { StructureHeaderTopEnabledArchive } from '../header/structure-header-top-enabled.archive';
import { StructureHeaderBottomEnabledArchive } from '../header/structure-header-bottom-enabled.archive';
export declare class StructureBlueprintComponent extends SmartComponent {
    private readonly changeDetectorRef;
    private readonly structureDefinition;
    private readonly structureId;
    private readonly structureReadModelService;
    private readonly pagingReadModelService;
    private readonly structureInfoPanelEnabledArchive;
    private readonly structureAggregationArchive;
    private readonly structureFilterReadModelRepository;
    private readonly structureSearchReadModelRepository;
    private readonly structureHeaderTopEnabledArchive;
    private readonly structureHeaderBottomEnabledArchive;
    private className;
    structure: StructureReadModelRoot;
    searchEnabled: boolean;
    topAggregationPanelEnabled: boolean;
    bottomAggregationPanelEnabled: boolean;
    quickFiltersEnabled: boolean;
    infoPanelEnabled: boolean;
    readonly contentCssClass: string;
    readonly headerCssClass: string;
    topHeaderEnabled: boolean;
    bottomHeaderEnabled: boolean;
    private pagingReadModel;
    constructor(changeDetectorRef: ChangeDetectorRef, structureDefinition: StructureDefinition, structureId: StructureId, structureReadModelService: StructureReadModelWarehouse, pagingReadModelService: StructurePagingReadModelWarehouse, structureInfoPanelEnabledArchive: StructureInfoPanelEnabledArchive, structureAggregationArchive: StructureAggregationArchive, structureFilterReadModelRepository: StructureFilterReadModelWarehouse, structureSearchReadModelRepository: StructureSearchReadModelRepository, structureHeaderTopEnabledArchive: StructureHeaderTopEnabledArchive, structureHeaderBottomEnabledArchive: StructureHeaderBottomEnabledArchive, className: string);
    ngOnInit(): void;
    getHeaderTopClasses(): string;
    getHeaderBottomClasses(): string;
    isColumnHeaderTopEnabled(): boolean;
    isColumnHeaderBottomEnabled(): boolean;
    isPagingTopEnabled(): boolean;
    isPagingBottomEnabled(): boolean;
    isSourceEmpty(): boolean;
}
