import { ChangeDetectorRef, ElementRef, OnInit } from '@angular/core';
import { SmartComponent } from '../../../../common/cdk/component/smart-component';
import { CellTemplateWithAccessor } from '../../../../composition/core/domain-read/definition/cell-template-with-accessor';
import { FormationCommandInvoker } from '../../../source/core/api/formation/formation.command-invoker';
import { StructureEditModeArchive } from '../edit/structure.edit-mode.archive';
import { FormationWarehouse } from '../../../source/core/api/formation/formation.warehouse';
import { ItemEntity } from '../../../source/core/domain/core/item/item.entity';
import { VerticalFormationRepository } from '../../../vertical-formation/core/api/vertical-formation.repository';
import { StructureWarehouse } from '../../core/api/structure.warehouse';
import { StructureId } from '../../../core/api/structure.id';
import { VerticalFormationWarehouse } from '../../../vertical-formation/core/api/vertical-formation.warehouse';
import { RowSelectionTypeArchive } from '../../../source/core/api/formation/type/row-selection-type.archive';
import { SchemaRowClassArchive } from '../../../../schema/core/api/styling/schema.row-class.archive';
import { SchemaRowStyleArchive } from '../../../../schema/core/api/styling/schema.row-style.archive';
import { SchemaRowClass } from '../../../../schema/core/api/styling/schema.row-class';
import { SchemaRowStyle } from '../../../../schema/core/api/styling/schema.row-style';
import { SearchWarehouse } from '../../../search/core/api/search.warehouse';
import { CellEditorManager } from '../../core/domain/edit/cell-editor.manager';
export declare class StructureContentComponent extends SmartComponent implements OnInit {
    private readonly elementRef;
    private readonly changeDetectorRef;
    private readonly formationCommandService;
    private readonly structureEditModeArchive;
    private readonly formationWarehouse;
    private readonly structureWarehouse;
    private readonly structureVerticalFormationWarehouse;
    private readonly verticalFormationRepository;
    private readonly structureId;
    private readonly rowSelectionTypeArchive;
    private readonly searchWarehouse;
    private readonly schemaRowClassArchive;
    private readonly schemaRowStyleArchive;
    source: Array<ItemEntity>;
    columns: Array<CellTemplateWithAccessor>;
    editMode: boolean;
    cellEditing: CellEditorManager;
    rowHeight: number;
    searchPhrase: string;
    highlighting: boolean;
    phrase: boolean;
    rowDetailOpened: number;
    checkboxSelection: boolean;
    schemaRowClass: SchemaRowClass;
    schemaRowStyle: SchemaRowStyle;
    constructor(elementRef: ElementRef, changeDetectorRef: ChangeDetectorRef, formationCommandService: FormationCommandInvoker, structureEditModeArchive: StructureEditModeArchive, formationWarehouse: FormationWarehouse, structureWarehouse: StructureWarehouse, structureVerticalFormationWarehouse: VerticalFormationWarehouse, verticalFormationRepository: VerticalFormationRepository, structureId: StructureId, // REfactor
    rowSelectionTypeArchive: RowSelectionTypeArchive, searchWarehouse: SearchWarehouse, schemaRowClassArchive: SchemaRowClassArchive, schemaRowStyleArchive: SchemaRowStyleArchive);
    ngOnInit(): void;
    trackByFn(): number;
    translateY(index: number): string;
    toggleSelectedRow(entity: ItemEntity): void;
    protected getSelectorName(): string;
}
