import { ModuleWithProviders } from '@angular/core';
import { FabricModalThemeService, FabricModule } from '@generic-ui/fabric';
import { StructureComponent } from './structure.component';
import { StructureHeaderComponent } from './header/structure-header.component';
import { StructureContentComponent } from './content/structure-content.component';
import { StructureRowComponent } from './content/row/structure-row.component';
import { StructureContainerComponent } from './content/structure-container.component';
import { StructureDefinition } from './structure-definition';
import { StructureModuleConfig } from './structure-module-config';
import { StructureCellEditArchive } from './edit/structure.cell-edit.archive';
import { StructurePublisher } from '../../core/structure/structure-core/api/structure.publisher';
import { StructureWarehouse } from '../../core/structure/structure-core/api/structure.warehouse';
import { StructureInitialValuesReadyArchive } from '../../core/structure/structure-core/api/ready/structure.initial-values-ready.archive';
import * as i0 from "@angular/core";
import * as i1 from "./structure.component";
import * as i2 from "./header/structure-header.component";
import * as i3 from "./header/column/structure-header-columns.component";
import * as i4 from "./header/group/structure-header-groups.component";
import * as i5 from "./header/filters/structure-header-filters.component";
import * as i6 from "./header/filters/structure.header-filter.component";
import * as i7 from "./header/column/select-all/select-all.component";
import * as i8 from "./content/structure-content.component";
import * as i9 from "./content/row/structure-row.component";
import * as i10 from "./content/cell/structure.cell.component";
import * as i11 from "./content/cell/edit/structure.cell-edit.component";
import * as i12 from "./content/cell/boolean/structure.cell-edit-boolean.component";
import * as i13 from "./content/structure-container.component";
import * as i14 from "./header/quick-filters/structure.quick-filters.component";
import * as i15 from "./blueprint/structure.blueprint.component";
import * as i16 from "./row-detail/view/structure.row-detail-view.component";
import * as i17 from "./panel/banner-panels/title-panel/structure.title-panel.component";
import * as i18 from "./panel/banner-panels/footer-panel/structure.footer-panel.component";
import * as i19 from "./gate/column/header/structure-column-header.gate";
import * as i20 from "./gate/paging/structure-paging.gate";
import * as i21 from "./gate/searching/structure-searching.gate";
import * as i22 from "./gate/source/structure-selection.gate";
import * as i23 from "./gate/l10n/structure-l10n.gate";
import * as i24 from "./gate/panel/structure-panel.gate";
import * as i25 from "./gate/row/detail/structure-row-detail.gate";
import * as i26 from "./gate/column/menu/structure-column-menu.gate";
import * as i27 from "../../feature/structure/summaries/gate/structure-summaries.gate";
import * as i28 from "./gate/panel/info/structure-info-panel.gate";
import * as i29 from "./gate/row/class/structure-row-class.gate";
import * as i30 from "./gate/row/style/structure-row-style.gate";
import * as i31 from "./gate/row/coloring/structure-row-coloring.gate";
import * as i32 from "../../feature/schema/gate/grid/theme-grid.gate";
import * as i33 from "../../feature/structure/sorting/gate/structure-sorting.gate";
import * as i34 from "./gate/source/source-loading.gate";
import * as i35 from "../../feature/structure/filter/gate/structure-filter.gate";
import * as i36 from "../../feature/structure/filter/gate/structure-quick-filters.gate";
import * as i37 from "../../feature/structure/vertical-formation/gate/vertical-formation.gate";
import * as i38 from "@angular/common";
import * as i39 from "@angular/forms";
import * as i40 from "../../feature/l10n/translation.feature-module";
import * as i41 from "@generic-ui/hermes";
import * as i42 from "@generic-ui/fabric";
import * as i43 from "../../feature/common/cdk/resize-detector/resize-detector.module";
import * as i44 from "../../feature/structure/paging/paging.feature-module";
import * as i45 from "../../feature/structure/sorting/sorting.feature-module";
import * as i46 from "../../feature/structure/field/field.feature-module";
import * as i47 from "../../feature/structure/formation/formation.feature-module";
import * as i48 from "../../feature/structure/search/search.feature-module";
import * as i49 from "../../feature/structure/filter/menu/filter-menu.feature-module";
import * as i50 from "../../feature/structure/source/source.feature-module";
import * as i51 from "../../feature/structure/summaries/summaries.feature-module";
import * as i52 from "../../feature/structure/vertical-formation/vertical-formation.feature-module";
import * as i53 from "../../feature/schema/schema.feature-module";
import * as i54 from "../../feature/structure/common/structure-shared.module";
import * as i55 from "./panel/info/structure.info-panel.module";
import * as i56 from "./panel/top/structure.top-panel.module";
import * as i57 from "./header/menu/structure.column-menu.module";
import * as i58 from "./column-manager/structure.column-manager.module";
import * as i59 from "../../feature/schema/manager/schema-manager.module";
import * as i60 from "../../feature/structure/source/empty/empty-source.feature-module";
import * as i61 from "../../feature/composition/composition.feature-module";
import * as i62 from "../../feature/common/cdk/logger/logger.module";
import * as i63 from "../../feature/common/cdk/sanitize/sanitize.module";
import * as i64 from "../../feature/common/icons/arrow/structure.arrow-icon.module";
import * as i65 from "../../feature/common/icons/menu/structure.menu-icon.module";
export declare function provideStructureCommandInvoker(): StructurePublisher;
export declare function provideStructureWarehouse(): StructureWarehouse;
export declare function provideStructureInitialValuesReadyArchive(): StructureInitialValuesReadyArchive;
export declare const structureProviders: ({
    provide: typeof StructurePublisher;
    useFactory: typeof provideStructureCommandInvoker;
} | {
    provide: typeof StructureWarehouse;
    useFactory: typeof provideStructureWarehouse;
} | {
    provide: typeof StructureInitialValuesReadyArchive;
    useFactory: typeof provideStructureInitialValuesReadyArchive;
})[];
export declare function createStructureDefinition(): StructureDefinition;
export declare function provideStructureCellEditArchive(): StructureCellEditArchive;
export declare function provideFabricModalThemeService(): FabricModalThemeService;
export declare class GridViewFeatureModule {
    private platformId;
    private static readonly HERMES_API;
    static exportDeclarations: (typeof FabricModule | typeof import("@generic-ui/fabric").FabricBadgeModule[] | typeof StructureComponent | typeof StructureHeaderComponent | typeof StructureContentComponent | typeof StructureRowComponent | typeof StructureContainerComponent | (typeof import("./gate/searching/structure-searching.gate").StructureSearchingGate | typeof import("./gate/column/header/structure-column-header.gate").StructureColumnHeaderGate | typeof import("./gate/paging/structure-paging.gate").StructurePagingGate | typeof import("./gate/source/structure-selection.gate").StructureSelectionGate | typeof import("./gate/l10n/structure-l10n.gate").StructureL10nGate | typeof import("./gate/panel/structure-panel.gate").StructurePanelGate | typeof import("./gate/row/detail/structure-row-detail.gate").StructureRowDetailGate | typeof import("./gate/column/menu/structure-column-menu.gate").StructureColumnMenuGate | typeof import("../../feature/structure/summaries/gate/structure-summaries.gate").StructureSummariesGate | typeof import("./gate/panel/info/structure-info-panel.gate").StructureInfoPanelGate | typeof import("./gate/row/class/structure-row-class.gate").StructureRowClassGate | typeof import("./gate/row/coloring/structure-row-coloring.gate").StructureRowColoringGate | typeof import("./gate/row/style/structure-row-style.gate").StructureRowStyleGate | typeof import("../../feature/schema/gate/grid/theme-grid.gate").ThemeGridGate | typeof import("./gate/source/source-loading.gate").SourceLoadingGate | typeof import("../../feature/structure/vertical-formation/gate/vertical-formation.gate").VerticalFormationGate | typeof import("../../feature/structure/sorting/gate/structure-sorting.gate").StructureSortingGate | typeof import("../../feature/structure/filter/gate/structure-filter.gate").StructureFilterGate | typeof import("../../feature/structure/filter/gate/structure-quick-filters.gate").StructureQuickFiltersGate)[])[];
    static withConfig(structureConfig?: StructureModuleConfig): ModuleWithProviders<GridViewFeatureModule>;
    constructor(platformId: any);
    static ɵfac: i0.ɵɵFactoryDeclaration<GridViewFeatureModule, never>;
    static ɵmod: i0.ɵɵNgModuleDeclaration<GridViewFeatureModule, [typeof i1.StructureComponent, typeof i2.StructureHeaderComponent, typeof i3.StructureHeaderColumnsComponent, typeof i4.StructureHeaderGroupsComponent, typeof i5.StructureHeaderFiltersComponent, typeof i6.StructureHeaderFilterComponent, typeof i7.SelectAllComponent, typeof i8.StructureContentComponent, typeof i9.StructureRowComponent, typeof i10.StructureCellComponent, typeof i11.StructureCellEditComponent, typeof i12.StructureCellEditBooleanComponent, typeof i13.StructureContainerComponent, typeof i14.StructureQuickFiltersComponent, typeof i15.StructureBlueprintComponent, typeof i16.StructureRowDetailViewComponent, typeof i17.StructureTitlePanelComponent, typeof i18.StructureFooterPanelComponent, typeof i19.StructureColumnHeaderGate, typeof i20.StructurePagingGate, typeof i21.StructureSearchingGate, typeof i22.StructureSelectionGate, typeof i23.StructureL10nGate, typeof i24.StructurePanelGate, typeof i25.StructureRowDetailGate, typeof i26.StructureColumnMenuGate, typeof i27.StructureSummariesGate, typeof i28.StructureInfoPanelGate, typeof i29.StructureRowClassGate, typeof i30.StructureRowStyleGate, typeof i31.StructureRowColoringGate, typeof i32.ThemeGridGate, typeof i33.StructureSortingGate, typeof i34.SourceLoadingGate, typeof i35.StructureFilterGate, typeof i36.StructureQuickFiltersGate, typeof i37.VerticalFormationGate], [typeof i38.CommonModule, typeof i39.ReactiveFormsModule, typeof i40.TranslationFeatureModule, typeof i41.HermesModule, typeof i42.FabricBadgeModule, typeof i42.FabricButtonModule, typeof i42.FabricButtonGroupModule, typeof i42.FabricCheckboxModule, typeof i42.FabricChipModule, typeof i42.FabricDrawerModule, typeof i42.FabricDropdownModule, typeof i42.FabricRadioButtonModule, typeof i42.FabricRadioGroupModule, typeof i42.FabricProgressBarModule, typeof i42.FabricProgressSpinnerModule, typeof i42.FabricSelectModule, typeof i42.FabricSpinnerModule, typeof i42.FabricTabModule, typeof i42.FabricTooltipModule, typeof i42.FabricToggleButtonModule, typeof i42.FabricInputModule, typeof i42.FabricDialogModule, typeof i42.FabricInlineDialogModule, typeof i42.FabricTabModule, typeof i43.ResizeDetectorModule, typeof i44.PagingFeatureModule, typeof i45.SortingFeatureModule, typeof i46.FieldFeatureModule, typeof i47.FormationFeatureModule, typeof i48.SearchFeatureModule, typeof i49.FilterMenuFeatureModule, typeof i50.SourceFeatureModule, typeof i51.SummariesFeatureModule, typeof i52.VerticalFormationFeatureModule, typeof i53.SchemaFeatureModule, typeof i54.StructureSharedModule, typeof i55.StructureInfoPanelModule, typeof i56.StructureTopPanelModule, typeof i57.StructureColumnMenuModule, typeof i58.StructureColumnManagerModule, typeof i59.SchemaManagerModule, typeof i60.EmptySourceFeatureModule, typeof i61.CompositionFeatureModule, typeof i62.LoggerModule, typeof i63.SanitizeModule, typeof i64.StructureArrowIconModule, typeof i65.StructureMenuIconModule], [typeof i42.FabricModule, typeof i1.StructureComponent, typeof i2.StructureHeaderComponent, typeof i8.StructureContentComponent, typeof i9.StructureRowComponent, typeof i13.StructureContainerComponent, typeof i42.FabricBadgeModule, typeof i42.FabricButtonModule, typeof i42.FabricButtonGroupModule, typeof i42.FabricCheckboxModule, typeof i42.FabricChipModule, typeof i42.FabricDrawerModule, typeof i42.FabricDropdownModule, typeof i42.FabricRadioButtonModule, typeof i42.FabricRadioGroupModule, typeof i42.FabricProgressBarModule, typeof i42.FabricProgressSpinnerModule, typeof i42.FabricSelectModule, typeof i42.FabricSpinnerModule, typeof i42.FabricTabModule, typeof i42.FabricTooltipModule, typeof i42.FabricToggleButtonModule, typeof i42.FabricInputModule, typeof i42.FabricDialogModule, typeof i42.FabricInlineDialogModule, typeof i42.FabricTabModule, typeof i44.PagingFeatureModule, typeof i19.StructureColumnHeaderGate, typeof i20.StructurePagingGate, typeof i21.StructureSearchingGate, typeof i22.StructureSelectionGate, typeof i23.StructureL10nGate, typeof i24.StructurePanelGate, typeof i25.StructureRowDetailGate, typeof i26.StructureColumnMenuGate, typeof i27.StructureSummariesGate, typeof i28.StructureInfoPanelGate, typeof i29.StructureRowClassGate, typeof i30.StructureRowStyleGate, typeof i31.StructureRowColoringGate, typeof i32.ThemeGridGate, typeof i33.StructureSortingGate, typeof i34.SourceLoadingGate, typeof i35.StructureFilterGate, typeof i36.StructureQuickFiltersGate, typeof i37.VerticalFormationGate]>;
    static ɵinj: i0.ɵɵInjectorDeclaration<GridViewFeatureModule>;
}
