import { AfterViewInit, ChangeDetectorRef, ElementRef, NgZone, OnDestroy, OnInit, Renderer2 } from '@angular/core';
import { ResizeDetector } from '@generic-ui/fabric';
import { SmartComponent } from '../../../../common/cdk/smart-component';
import { CellTemplateWithAccessor } from '../../../composition/read/definition/cell-template-with-accessor';
import { SchemaRowColoring } from '../../../schema/domain/schema-row-coloring';
import { StructureId } from '../../domain/structure.id';
import { StructureCommandDispatcher } from '../../ui-api/structure.command-dispatcher';
import { StructureWarehouse } from '../../ui-api/structure.warehouse';
import { StructureSourceWarehouse } from '../../ui-api/source/structure-source.warehouse';
import { CompositionCommandDispatcher } from '../../../composition/ui-api/composition.command-dispatcher';
import { CompositionWarehouse } from '../../../composition/ui-api/composition.warehouse';
import { StructureFormationWarehouse } from '../../ui-api/formation/structure-formation.warehouse';
import { ItemEntity } from '../../domain/source/item.entity';
import { StructureVerticalFormationWarehouse } from '../../ui-api/vertical-formation/structure-vertical-formation.warehouse';
export declare class StructureContainerComponent extends SmartComponent implements OnInit, AfterViewInit, OnDestroy {
    private readonly elementRef;
    private readonly renderer;
    private readonly changeDetectorRef;
    private readonly ngZone;
    private readonly structureId;
    private readonly structureCommandService;
    private readonly structureReadModelWarehouse;
    private readonly structureVerticalFormationWarehouse;
    private readonly sourceReadModelService;
    private readonly compositionCommandService;
    private readonly compositionReadModelService;
    private readonly formationReadModelService;
    private readonly resizeDetector;
    private readonly structureParent;
    sourceCollectionRef: ElementRef;
    columns: Array<CellTemplateWithAccessor>;
    source: Array<ItemEntity>;
    height: number;
    rowColoring: SchemaRowColoring;
    private autoResizeWidthEnabled;
    private scrollObservation$;
    constructor(elementRef: ElementRef, renderer: Renderer2, changeDetectorRef: ChangeDetectorRef, ngZone: NgZone, structureId: StructureId, structureCommandService: StructureCommandDispatcher, structureReadModelWarehouse: StructureWarehouse, structureVerticalFormationWarehouse: StructureVerticalFormationWarehouse, sourceReadModelService: StructureSourceWarehouse, compositionCommandService: CompositionCommandDispatcher, compositionReadModelService: CompositionWarehouse, formationReadModelService: StructureFormationWarehouse, resizeDetector: ResizeDetector, structureParent: any);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    private setContainerHeight;
    private setSourceHeight;
    private recalculateContainer;
    private enableScrollObservation;
    private disableScrollObservation;
}
