import { ChangeDetectorRef, ElementRef, OnInit, Renderer2 } from '@angular/core';
import { SmartComponent } from '../../../../common/cdk/smart-component';
import { CellTemplateWithAccessor } from '../../../composition/domain/read/definition/cell-template-with-accessor';
import { FormationCommandService } from '../../ui-api/formation/formation-command.service';
import { StructureCellEditArchive } from '../edit/structure.cell-edit.archive';
import { StructureEditModeArchive } from '../edit/structure.edit-mode.archive';
import { FormationReadModelService } from '../../ui-api/formation/formation-read-model.service';
import { ItemEntity } from '../../domain/source/item.entity';
import { VerticalFormationRepository } from '../../domain/structure/read/vertical-formation/vertical-formation.repository';
import { StructureReadModelService } from '../../ui-api/structure/structure-read-model.service';
export declare class StructureContentComponent extends SmartComponent implements OnInit {
    private platformId;
    private renderer;
    private elementRef;
    private changeDetectorRef;
    private formationCommandService;
    private structureCellEditArchive;
    private structureEditModeArchive;
    private formationQueryService;
    private structureReadModelService;
    private verticalFormationRepository;
    source: Array<ItemEntity>;
    columns: Array<CellTemplateWithAccessor>;
    editMode: boolean;
    cellEditing: boolean;
    rowHeight: number;
    constructor(platformId: any, renderer: Renderer2, elementRef: ElementRef, changeDetectorRef: ChangeDetectorRef, formationCommandService: FormationCommandService, structureCellEditArchive: StructureCellEditArchive, structureEditModeArchive: StructureEditModeArchive, formationQueryService: FormationReadModelService, structureReadModelService: StructureReadModelService, verticalFormationRepository: VerticalFormationRepository);
    ngOnInit(): void;
    trackByFn(): number;
    translateY(index: number): string;
    toggleSelectedRow(entity: ItemEntity): void;
    private clearSelectedRows;
}
