import { ChangeDetectorRef, ElementRef } from '@angular/core';
import { SmartComponent } from '../../../../feature/common/component/src/smart-component';
import { PagingModel } from '../../../../core/structure/paging/src/api/model/paging.model';
import { StructureDefinition } from '../structure/structure-definition';
import { StructureId } from '../../../../core/structure/structure-core/src/api/global/structure.id';
import { StructureWarehouse } from '../../../../core/structure/structure-core/src/api/structure.warehouse';
import { PagingWarehouse } from '../../../../core/structure/paging/src/api/paging.warehouse';
import { StructureInfoPanelArchive } from '../../../../core/structure/structure-core/src/api/panel/info/structure.info-panel.archive';
import { FilterWarehouse } from '../../../../core/structure/filter/src/api/filter.warehouse';
import { SearchWarehouse } from '../../../../core/structure/search/src/api/search.warehouse';
import { StructureHeaderTopEnabledArchive } from '../header/structure-header-top-enabled.archive';
import { StructureHeaderBottomEnabledArchive } from '../header/structure-header-bottom-enabled.archive';
import { StructureTitlePanelConfigArchive } from '../panel/banner-panels/title-panel/structure.title-panel.config-archive';
import { StructureFooterPanelConfigArchive } from '../panel/banner-panels/footer-panel/structure.footer-panel.config-archive';
import { SummariesWarehouse } from '../../../../core/structure/summaries/src/api/summaries.warehouse';
import { HermesObservable } from '@generic-ui/hermes';
import * as i0 from "@angular/core";
export declare class StructureBlueprintComponent extends SmartComponent {
    private readonly changeDetectorRef;
    private readonly structureDefinition;
    private readonly structureId;
    private readonly structureWarehouse;
    private readonly structureInfoPanelArchive;
    private readonly pagingWarehouse;
    private readonly summariesWarehouse;
    private readonly filterWarehouse;
    private readonly searchWarehouse;
    private readonly structureHeaderTopEnabledArchive;
    private readonly structureHeaderBottomEnabledArchive;
    private readonly structureTitlePanelConfigArchive;
    private readonly structureFooterPanelConfigArchive;
    private className;
    readonly bottomSummariesPanelEnabled$: HermesObservable<boolean>;
    readonly contentCssClass: string;
    readonly headerCssClass: string;
    readonly headerTopClasses: string;
    readonly headerBottomClasses: string;
    readonly topHeaderEnabled$: HermesObservable<boolean>;
    readonly bottomHeaderEnabled$: HermesObservable<boolean>;
    readonly footerPanelEnabled$: HermesObservable<boolean>;
    readonly items$: HermesObservable<any>;
    readonly topSummariesPanelEnabled$: HermesObservable<boolean>;
    readonly searchEnabled$: HermesObservable<boolean>;
    readonly titlePanelEnabled$: HermesObservable<boolean>;
    readonly infoPanelEnabled$: HermesObservable<boolean>;
    readonly pagingModel$: HermesObservable<PagingModel>;
    constructor(changeDetectorRef: ChangeDetectorRef, elementRef: ElementRef, structureDefinition: StructureDefinition, structureId: StructureId, structureWarehouse: StructureWarehouse, structureInfoPanelArchive: StructureInfoPanelArchive, pagingWarehouse: PagingWarehouse, summariesWarehouse: SummariesWarehouse, filterWarehouse: FilterWarehouse, searchWarehouse: SearchWarehouse, structureHeaderTopEnabledArchive: StructureHeaderTopEnabledArchive, structureHeaderBottomEnabledArchive: StructureHeaderBottomEnabledArchive, structureTitlePanelConfigArchive: StructureTitlePanelConfigArchive, structureFooterPanelConfigArchive: StructureFooterPanelConfigArchive, className: string);
    isColumnHeaderTopEnabled(topHeaderEnabled: boolean): boolean;
    isColumnHeaderBottomEnabled(bottomHeaderEnabled: boolean): boolean;
    isPagingTopEnabled(pagingModel: PagingModel): boolean;
    isPagingBottomEnabled(pagingModel: PagingModel): boolean;
    protected getSelectorName(): string;
    private selectTitlePanelEnabled;
    private selectInfoPanelEnabled;
    private selectFooterPanelEnabled;
    private selectItems;
    static ɵfac: i0.ɵɵFactoryDeclaration<StructureBlueprintComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<StructureBlueprintComponent, "div[gui-structure-blueprint]", never, {}, {}, never, never, false, never>;
}
