import { CellView } from '../../cell-view';
import { ColumnId } from './column.id';
import { ColumnField } from './field/column-field';
import { ColumnConfig, HeaderTemplate } from '../../column.config';
import { SortOrder } from './sort/sort-order';
import { ViewEntity } from './view.entity';
import { DataType } from '../../../../structure/domain/structure/command/field/data-type/data-type';
export declare class ColumnEntity {
    columnId: ColumnId;
    columnField: ColumnField;
    header?: string | HeaderTemplate;
    sortOrder: SortOrder;
    width?: number;
    sortable?: boolean;
    private enabled;
    private columnConfig;
    private view;
    constructor(columnId: ColumnId, columnField: ColumnField, columnConfig: ColumnConfig, header?: string | HeaderTemplate, view?: ViewEntity, width?: number);
    getColumnConfig(): ColumnConfig;
    getColumnId(): ColumnId;
    isEnabled(): boolean;
    setEnabled(enabled: boolean): void;
    getField(): ColumnField;
    getHeader(): string | HeaderTemplate;
    getDataType(): DataType;
    getCellView(): CellView;
    getTemplateFunction(): any;
    setSortStatus(status: SortOrder): void;
    setView(view: ViewEntity): void;
    getView(): ViewEntity;
    getSortingEnabled(): boolean;
}
