import { CommandDispatcher } from '@generic-ui/hermes';
import { StructureCommandService } from '../../../ui-api/structure/structure-command.service';
import { StructureId } from '../../../domain/structure-id';
import { CompositionId } from '../../../../composition/domain/composition-id';
import { StructureFilterCommandService } from '../../../ui-api/structure/filter/structure.filter.command.service';
import { SourceDispatcher } from '../../../domain/source/command/source.dispatcher';
import { SortingConfig } from '../../../ui-api/structure/sorting-config';
import { FieldId } from '../../../domain/structure/command/field/data-type/field.id';
import { FilterConfig } from '../../../ui-api/structure/filter/filter-config';
import { QuickFiltersConfig } from '../../../ui-api/structure/filter/quick-filters.config';
import { SearchConfig } from '../../../ui-api/structure/search/search-config';
import { ColumnConfig } from '../../../../composition/domain/column.config';
import { SortOrder } from '../../../../composition/domain/command/column/sort/sort-order';
import { StructureSearchDispatcher } from '../../../domain/structure/command/search/structure.search.dispatcher';
export declare class LocalStructureCommandService extends StructureCommandService {
    private readonly structureId;
    private readonly compositionId;
    constructor(structureId: StructureId, compositionId: CompositionId, commandDispatcher: CommandDispatcher, structureFilterCommandService: StructureFilterCommandService, sourceDispatcher: SourceDispatcher, structureSearchDispatcher: StructureSearchDispatcher);
    init(): void;
    enableVerticalScroll(): void;
    disableVerticalScroll(): void;
    setScrollPosition(position: number): void;
    setOrigin(items: Array<any>): void;
    setSortingConfig(config: SortingConfig, structureId?: StructureId): void;
    toggleSort(fieldId: FieldId): void;
    setSortOrder(fieldId: FieldId, sortOrder: SortOrder): void;
    setFilterConfig(config: FilterConfig, structureId?: StructureId): void;
    setQuickFiltersConfig(config: QuickFiltersConfig, structureId?: StructureId): void;
    initFields(columns: Array<ColumnConfig>): void;
    setSearchingConfig(config: SearchConfig, structureId?: StructureId): void;
    search(phrase: string): void;
    setRowHeight(rowHeight: number): void;
}
