import { ChangeDetectorRef, ElementRef, OnInit } from '@angular/core';
import { CellTemplateWithContext } from '../../../../core/composition/domain-read/definition/cell-template-with-context';
import { SmartComponent } from '../../../common/cdk/component/smart-component';
import { CompositionWarehouse } from '../../../../core/composition/api/composition.warehouse';
import { FieldWarehouse } from '../../../../core/structure/field/api/field.warehouse';
import { StructureId } from '../../../../core/structure/core/api/global/structure.id';
import { FieldModel } from '../../../../core/structure/field/api/model/field.model';
import { FilterWarehouse } from '../../../../core/structure/filter/api/filter.warehouse';
import { FilterTypeCollectionModel } from '../../../../core/structure/filter/api/type/filter-type-collection.model';
import { FilterTypeModel } from '../../../../core/structure/filter/api/type/filter-type.model';
import { FilterTypeId } from '../../../../core/structure/filter/domain/type/filter-type.id';
import { FilterPublisher } from '../../../../core/structure/filter/api/filter.publisher';
import { ActiveFilterModel } from '../../../../core/structure/filter/api/active/active-filter.model';
import { CompositionId } from '../../../../core/composition/api/global/composition.id';
import { FilterId } from '../../../../core/structure/filter/api/id/filter.id';
import * as i0 from "@angular/core";
export declare class FilterMenuComponent extends SmartComponent implements OnInit {
    private readonly structureId;
    private readonly compositionId;
    private readonly fieldWarehouse;
    private readonly filterWarehouse;
    private readonly filterCommandInvoker;
    private readonly compositionWarehouse;
    selectedColumn: CellTemplateWithContext;
    columns: Array<CellTemplateWithContext>;
    selectedField: FieldModel;
    fields: Array<FieldModel>;
    filterTypeMap: FilterTypeCollectionModel;
    filterTypes: Array<FilterTypeModel>;
    selectedFilterTypeId: FilterTypeId;
    selectedValue: string;
    activeFilters: Array<ActiveFilterModel>;
    constructor(changeDetectorRef: ChangeDetectorRef, elementRef: ElementRef, structureId: StructureId, compositionId: CompositionId, fieldWarehouse: FieldWarehouse, filterWarehouse: FilterWarehouse, filterCommandInvoker: FilterPublisher, compositionWarehouse: CompositionWarehouse);
    ngOnInit(): void;
    onFieldSelect(field: FieldModel): void;
    onFilterTypeSelect(filterTypeId: FilterTypeId): void;
    removeAllFilters(): void;
    onValueChanged(value: string): void;
    addFilter(): void;
    onRemovedFilter(filterId: FilterId): void;
    removeFilter(): void;
    clearAddFilterForm(): void;
    protected getSelectorName(): string;
    static ɵfac: i0.ɵɵFactoryDeclaration<FilterMenuComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<FilterMenuComponent, "div[gui-filter-menu]", never, {}, {}, never, never>;
}
